// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NpsPesquisa.Api.Data;

#nullable disable

namespace NpsPesquisa.Api.Migrations
{
    [DbContext(typeof(NpsDbContext))]
    [Migration("20250524055547_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NpsPesquisa.Api.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AceitaContato")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Filial")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("NivelEnsino")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("PeriodoLetivo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("EmailInstitucional")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("EmailPessoal")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("Fone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("StatusNoPeriodoLetivo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasCharSet("utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.ConviteQuestionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataResposta")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("QuestionarioId")
                        .HasColumnType("int");

                    b.Property<bool>("Respondido")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.HasIndex("QuestionarioId");

                    b.ToTable("ConvitesQuestionarios");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.OpcaoQuestao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Valor")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoId");

                    b.ToTable("OpcoesQuestoes");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Perfis");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.Questao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Questoes");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.QuestaoQuestionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoId");

                    b.HasIndex("QuestionarioId");

                    b.ToTable("QuestoesQuestionarios");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.Questionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Questionarios");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.Resposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataResposta")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("QuestionarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("QuestionarioId");

                    b.ToTable("Respostas");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.RespostaQuestao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("int");

                    b.Property<int>("RespostaId")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoId");

                    b.HasIndex("RespostaId");

                    b.ToTable("RespostasQuestoes");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.Aluno", b =>
                {
                    b.HasOne("NpsPesquisa.Api.Models.Curso", "Curso")
                        .WithMany("Alunos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.ConviteQuestionario", b =>
                {
                    b.HasOne("NpsPesquisa.Api.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NpsPesquisa.Api.Models.Questionario", "Questionario")
                        .WithMany()
                        .HasForeignKey("QuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Questionario");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.OpcaoQuestao", b =>
                {
                    b.HasOne("NpsPesquisa.Api.Models.Questao", "Questao")
                        .WithMany("Opcoes")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.QuestaoQuestionario", b =>
                {
                    b.HasOne("NpsPesquisa.Api.Models.Questao", "Questao")
                        .WithMany("QuestoesQuestionarios")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NpsPesquisa.Api.Models.Questionario", "Questionario")
                        .WithMany("QuestoesQuestionarios")
                        .HasForeignKey("QuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");

                    b.Navigation("Questionario");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.Resposta", b =>
                {
                    b.HasOne("NpsPesquisa.Api.Models.Aluno", "Aluno")
                        .WithMany("Respostas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NpsPesquisa.Api.Models.Questionario", "Questionario")
                        .WithMany("Respostas")
                        .HasForeignKey("QuestionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Questionario");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.RespostaQuestao", b =>
                {
                    b.HasOne("NpsPesquisa.Api.Models.Questao", "Questao")
                        .WithMany()
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NpsPesquisa.Api.Models.Resposta", "Resposta")
                        .WithMany("RespostasQuestoes")
                        .HasForeignKey("RespostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");

                    b.Navigation("Resposta");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.Usuario", b =>
                {
                    b.HasOne("NpsPesquisa.Api.Models.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.Aluno", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.Curso", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.Questao", b =>
                {
                    b.Navigation("Opcoes");

                    b.Navigation("QuestoesQuestionarios");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.Questionario", b =>
                {
                    b.Navigation("QuestoesQuestionarios");

                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.Resposta", b =>
                {
                    b.Navigation("RespostasQuestoes");
                });
#pragma warning restore 612, 618
        }
    }
}
