// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NpsPesquisa.Api.Data;

#nullable disable

namespace NpsPesquisa.Api.Migrations
{
    [DbContext(typeof(NpsDbContext))]
    [Migration("20250603095906_AddMissingAlunoFields")]
    partial class AddMissingAlunoFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NpsPesquisa.Api.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AceitaContato")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("EmailInstitucional")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("EmailPessoal")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("Fone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("NivelEnsino")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("PeriodoLetivo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("StatusNoPeriodoLetivo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasCharSet("utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("NpsPesquisa.Api.Models.Aluno", b =>
                {
                    b.HasOne("NpsPesquisa.Api.Models.Curso", "Curso")
                        .WithMany("Alunos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");
                });
#pragma warning restore 612, 618
        }
    }
} 